export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      hotel_settings: { Row: { id:string; name:string; city:string; address:string; phone:string|null; check_in:string; check_out:string; tax_percent:number; timezone:string; created_at:string; updated_at:string }; Insert: Partial<Database['public']['Tables']['hotel_settings']['Row']> & { name:string; address:string }; Update: Partial<Database['public']['Tables']['hotel_settings']['Row']> };
      staff_profiles: { Row: { user_id:string; display_name:string; role:string; active:boolean; created_at:string }; Insert: Omit<Database['public']['Tables']['staff_profiles']['Row'],'created_at'> & { created_at?:string }; Update: Partial<Database['public']['Tables']['staff_profiles']['Row']> };
      room_types: { Row: { id:string; name:string; slug:string; description:string|null; max_guests:number; size_sqft:number|null; base_price:number; bed_description:string|null; active:boolean; created_at:string }; Insert: Partial<Database['public']['Tables']['room_types']['Row']> & { name:string; slug:string; base_price:number }; Update: Partial<Database['public']['Tables']['room_types']['Row']> };
      rooms: { Row: { id:string; room_type_id:string; room_number:string; floor:number|null; status:Database['public']['Enums']['room_status']; active:boolean; created_at:string }; Insert: Partial<Database['public']['Tables']['rooms']['Row']> & { room_type_id:string; room_number:string }; Update: Partial<Database['public']['Tables']['rooms']['Row']> };
      guests: { Row: { id:string; full_name:string; phone:string|null; email:string|null; notes:string|null; created_at:string; updated_at:string }; Insert: Partial<Database['public']['Tables']['guests']['Row']> & { full_name:string }; Update: Partial<Database['public']['Tables']['guests']['Row']> };
      reservations: { Row: { id:string; confirmation_code:string; guest_id:string; room_id:string; check_in:string; check_out:string; guests:number; status:Database['public']['Enums']['booking_status']; source:string; nightly_rate:number; subtotal:number; tax:number; total:number; notes:string|null; created_by:string|null; created_at:string; updated_at:string }; Insert: Omit<Database['public']['Tables']['reservations']['Row'],'id'|'created_at'|'updated_at'> & { id?:string; created_at?:string; updated_at?:string }; Update: Partial<Database['public']['Tables']['reservations']['Row']> };
      room_blocks: { Row: { id:string; room_id:string; start_date:string; end_date:string; reason:string; created_by:string|null; created_at:string }; Insert: Omit<Database['public']['Tables']['room_blocks']['Row'],'id'|'created_at'> & { id?:string; created_at?:string }; Update: Partial<Database['public']['Tables']['room_blocks']['Row']> };
      services: { Row: { id:string; name:string; price:number; pricing_mode:string; active:boolean; created_at:string }; Insert: Partial<Database['public']['Tables']['services']['Row']> & { name:string; price:number; pricing_mode:string }; Update: Partial<Database['public']['Tables']['services']['Row']> };
      reservation_services: { Row: { id:string; reservation_id:string; service_id:string; quantity:number; unit_price:number; created_at:string }; Insert: Partial<Database['public']['Tables']['reservation_services']['Row']> & { reservation_id:string; service_id:string; unit_price:number }; Update: Partial<Database['public']['Tables']['reservation_services']['Row']> };
      payments: { Row: { id:string; reservation_id:string; amount:number; method:string; status:string; reference:string|null; paid_at:string|null; created_at:string }; Insert: Partial<Database['public']['Tables']['payments']['Row']> & { reservation_id:string; amount:number; method:string }; Update: Partial<Database['public']['Tables']['payments']['Row']> };
      media_assets: { Row: { id:string; kind:string; storage_path:string; public_url:string|null; title:string|null; alt_text:string|null; version:number; published:boolean; created_by:string|null; created_at:string }; Insert: Partial<Database['public']['Tables']['media_assets']['Row']> & { kind:string; storage_path:string }; Update: Partial<Database['public']['Tables']['media_assets']['Row']> };
      audit_events: { Row: { id:number; actor_user_id:string|null; action:string; entity_type:string|null; entity_id:string|null; before_data:Json|null; after_data:Json|null; created_at:string }; Insert: Partial<Database['public']['Tables']['audit_events']['Row']> & { action:string }; Update: Partial<Database['public']['Tables']['audit_events']['Row']> };
      hotel_reviews: { Row: { id:string; source:string; rating:number|null; title:string|null; body:string|null; review_date:string|null; response:string|null; published:boolean; created_at:string }; Insert: Partial<Database['public']['Tables']['hotel_reviews']['Row']> & { source:string }; Update: Partial<Database['public']['Tables']['hotel_reviews']['Row']> };
    };
    Functions: {
      calculate_reservation_total: { Args:{ p_room_type_id:string; p_check_in:string; p_check_out:string; p_guests?:number }; Returns:{ nights:number; nightly_rate:number; subtotal:number; tax:number; total:number }[] };
      create_website_reservation: { Args:{ p_room_type_id:string; p_check_in:string; p_check_out:string; p_guests:number; p_full_name:string; p_phone:string; p_email?:string|null; p_notes?:string|null }; Returns:{ reservation_id:string; confirmation_code:string; room_number:string; room_type:string; check_in:string; check_out:string; total:number }[] };
      is_hotel_staff: { Args:Record<string, never>; Returns:boolean };
      get_available_room_types: { Args:{ p_check_in:string; p_check_out:string; p_guests?:number }; Returns:{ id:string; name:string; slug:string; description:string|null; max_guests:number; size_sqft:number; base_price:number; bed_description:string|null; available_rooms:number }[] };
    };
    Enums: {
      booking_status:'pending'|'confirmed'|'checked_in'|'in_house'|'checked_out'|'cancelled'|'no_show';
      room_status:'vacant'|'dirty'|'cleaning'|'clean'|'inspected'|'out_of_order'|'maintenance';
    };
  };
};