import { useEffect, useRef, useState } from 'react';
import * as pdfjsLib from 'pdfjs-dist';
import { ChevronLeft, ChevronRight, Download, Maximize2, Upload } from 'lucide-react';

pdfjsLib.GlobalWorkerOptions.workerSrc = new URL('pdfjs-dist/build/pdf.worker.min.mjs', import.meta.url).toString();

type Props = { file: Blob | string | null; fileName?: string; onUpload?: (file: File) => void };

export default function Flipbook({ file, fileName, onUpload }: Props) {
  const [pdf, setPdf] = useState<any>(null); const [page,setPage]=useState(1); const [busy,setBusy]=useState(false); const canvasRef=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{let alive=true;if(!file){setPdf(null);setPage(1);return;}setBusy(true);const url=typeof file==='string'?file:URL.createObjectURL(file);pdfjsLib.getDocument(url).promise.then((doc:any)=>{if(alive){setPdf(doc);setPage(1)}else{doc.destroy()}}).finally(()=>{if(alive)setBusy(false)});return()=>{alive=false;if(typeof file!=='string')URL.revokeObjectURL(url)}},[file]);
  useEffect(()=>{let cancelled=false;if(!pdf||!canvasRef.current)return;pdf.getPage(page).then((p:any)=>{if(cancelled||!canvasRef.current)return;const base=p.getViewport({scale:1});const width=Math.min(820,canvasRef.current.parentElement?.clientWidth||820);const viewport=p.getViewport({scale:width/base.width});const canvas=canvasRef.current;const context=canvas.getContext('2d')!;canvas.width=viewport.width;canvas.height=viewport.height;p.render({canvasContext:context,viewport})});return()=>{cancelled=true}},[pdf,page]);
  const [downloadUrl,setDownloadUrl]=useState('');
  useEffect(()=>{if(!file){setDownloadUrl('');return;}if(typeof file==='string'){setDownloadUrl(file);return;}const url=URL.createObjectURL(file);setDownloadUrl(url);return()=>URL.revokeObjectURL(url)},[file]);
  return <div className="flipbook-card"><div className="flipbook-toolbar"><div><strong>{fileName||'No menu PDF uploaded'}</strong><span>{pdf?pdf.numPages+' pages':'Upload the current menu PDF'}</span></div><div className="flip-actions">{onUpload&&<label className="icon-btn" title="Upload PDF"><Upload size={16}/><input type="file" accept="application/pdf" hidden onChange={e=>e.target.files?.[0]&&onUpload(e.target.files[0])}/></label>}{file&&<a className="icon-btn" href={downloadUrl} download={fileName||'bhola-inn-menu.pdf'} title="Download PDF"><Download size={16}/></a>}</div></div><div className="flipbook-stage">{busy&&<div className="flip-loading">Loading menu…</div>}{!busy&&pdf&&<><button className="page-nav left" disabled={page<=1} onClick={()=>setPage(p=>Math.max(1,p-1))}><ChevronLeft size={20}/></button><div className="paper-wrap"><div className="paper"><canvas ref={canvasRef}/></div></div><button className="page-nav right" disabled={page>=pdf.numPages} onClick={()=>setPage(p=>Math.min(pdf.numPages,p+1))}><ChevronRight size={20}/></button></>}{!busy&&!pdf&&<div className="flip-empty"><div className="flip-empty-icon">PDF</div><h3>Turn your menu into a digital flipbook</h3><p>Upload the menu once in Admin → Dining & Menu. Guests can browse the published file page by page.</p>{onUpload&&<label className="primary-btn">Upload menu PDF<input type="file" accept="application/pdf" hidden onChange={e=>e.target.files?.[0]&&onUpload(e.target.files[0])}/></label>}</div>}</div>{pdf&&<div className="flip-footer"><span>Page {page} / {pdf.numPages}</span><div className="page-dots">{Array.from({length:Math.min(pdf.numPages,12)},(_,i)=><button key={i} aria-label={'Go to page '+(i+1)} className={page===i+1?'dot active':'dot'} onClick={()=>setPage(i+1)}/>)}</div><button className="quiet-btn" onClick={()=>document.querySelector('.flipbook-stage')?.requestFullscreen?.()}><Maximize2 size={14}/> Fullscreen</button></div>}</div>
}