import { useEffect, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, BedDouble, CalendarDays, Check, ChevronRight, Clock3, FileText, GalleryHorizontal, Gauge, House, LogOut, Menu, MessageSquareText, Plus, Search, Settings, ShieldCheck, Users, X, Utensils } from 'lucide-react';
import { amenities, hotel, photos, reviews, rooms } from './data/bhola';
import Flipbook from './components/Flipbook';
import { calculateBookingTotal, isRoomAvailable, transitionReservation } from './lib/booking.mjs';
import { appendAudit, loadStore, saveStore } from './lib/store.mjs';
import { loadMenu, saveMenu } from './lib/menuStore.mjs';
import { supabase } from './lib/supabase';
import { createWebsiteReservation, getAdminData, getPublicAvailability, signInAdmin, signOutAdmin, updateReservationStatus, updateRoomStatus } from './lib/hotelApi';

const nav = [
  ['dashboard','Dashboard',Gauge],['reservations','Reservations',CalendarDays],['rooms','Rooms & Inventory',BedDouble],
  ['calendar','Availability',Clock3],['dining','Dining & Menu',Utensils],['guests','Guest CRM',Users],['housekeeping','Housekeeping',House],
  ['payments','Payments',ShieldCheck],['reviews','Reviews',MessageSquareText],['media','Gallery & CMS',GalleryHorizontal],['settings','Settings',Settings],
] as const;

function Header({onAdmin}:{onAdmin:()=>void}){return <header className="topbar"><a className="brand" href="#top"><span className="brand-mark">BI</span><span>BHOLA <b>INN</b></span></a><div className="top-meta"><span className="live"><i/> LIVE BOOKING ENGINE</span><span>STATION CHOWK / BETTIAH</span></div><div className="top-actions"><a href={'tel:'+hotel.phone.replace(/\s/g,'')} className="text-button">Call hotel <ArrowUpRight size={14}/></a><button className="menu-pill" onClick={onAdmin}>ADMIN <Menu size={15}/></button></div></header>}

function getDefaultStay(){const d=new Date();const checkIn=new Date(d);checkIn.setDate(d.getDate()+1);const checkOut=new Date(d);checkOut.setDate(d.getDate()+2);const fmt=(x:Date)=>x.toISOString().slice(0,10);return {checkIn:fmt(checkIn),checkOut:fmt(checkOut)}}
function BookingBar({onSearch}:{onSearch:(x:{checkIn:string;checkOut:string;guests:number})=>void}){const defaults=getDefaultStay();const [checkIn,setCheckIn]=useState(defaults.checkIn);const [checkOut,setCheckOut]=useState(defaults.checkOut);const [guests,setGuests]=useState(2);return <div className="booking-bar"><div><span>CHECK-IN</span><input type="date" value={checkIn} onChange={e=>setCheckIn(e.target.value)}/></div><div><span>CHECK-OUT</span><input type="date" value={checkOut} onChange={e=>setCheckOut(e.target.value)}/></div><div><span>GUESTS</span><select value={guests} onChange={e=>setGuests(Number(e.target.value))}><option>1</option><option>2</option><option>3</option><option>4</option></select></div><button onClick={()=>onSearch({checkIn,checkOut,guests})}>CHECK AVAILABILITY <ArrowDownRight size={16}/></button></div>}

function PublicSite({onAdmin}:{onAdmin:()=>void}){
  const [publishedMenu,setPublishedMenu]=useState<any>(null);
  const [bookingSearch,setBookingSearch]=useState<any>(null);
  const [availableTypes,setAvailableTypes]=useState<any[]>([]);
  const [selectedRoom,setSelectedRoom]=useState<any>(null);
  const [bookingDone,setBookingDone]=useState(false);
  const [bookingConfirmation,setBookingConfirmation]=useState<any>(null);
  const [bookingLoading,setBookingLoading]=useState(false);
  const [bookingError,setBookingError]=useState('');
  useEffect(()=>{loadMenu().then(setPublishedMenu)},[]);
  const currentAvailable=bookingSearch?(availableTypes.length?availableTypes:[]):rooms;
  const loadAvailability=async(search:any)=>{
    try{
      setBookingError('');
      const data=await getPublicAvailability(search.checkIn,search.checkOut,search.guests);
      const mapped=data.map((item:any)=>{
        const local=rooms.find(r=>r.id===item.slug);
        return local?{...local,dbRoomTypeId:item.id,price:Number(item.base_price),availableRooms:Number(item.available_rooms),maxGuests:item.max_guests}:null;
      }).filter(Boolean);
      setAvailableTypes(mapped as any[]);
      return mapped as any[];
    }catch(error){setBookingError(error instanceof Error?error.message:'Could not load availability.');setAvailableTypes([]);return []}
  };
  const handleSearch=async(search:any)=>{setBookingSearch(search);await loadAvailability(search)};
  const handleReserve=async(room:any)=>{
    const search=bookingSearch||{...getDefaultStay(),guests:2};
    setBookingSearch(search);
    const available=await loadAvailability(search);
    const liveRoom=available.find((x:any)=>x.id===room.id&&x.availableRooms>0);
    if(!liveRoom){setBookingError('That room type is unavailable for the selected dates.');return;}
    setSelectedRoom(liveRoom);
    setBookingDone(false);
    setBookingConfirmation(null);
  };
  const submit=async(e:React.FormEvent<HTMLFormElement>)=>{
    e.preventDefault();
    if(!selectedRoom||!bookingSearch)return;
    const fd=new FormData(e.currentTarget);
    setBookingLoading(true);setBookingError('');
    try{
      const result=await createWebsiteReservation({
        roomTypeId:selectedRoom.dbRoomTypeId,
        checkIn:bookingSearch.checkIn,
        checkOut:bookingSearch.checkOut,
        guests:bookingSearch.guests,
        fullName:String(fd.get('guest')||'').trim(),
        phone:String(fd.get('phone')||'').trim(),
        email:String(fd.get('email')||'').trim()||undefined,
        notes:String(fd.get('notes')||'').trim()||undefined,
      });
      setBookingConfirmation(result);
      setBookingDone(true);
      await loadAvailability(bookingSearch);
    }catch(error){setBookingError(error instanceof Error?error.message:'Reservation failed. Please try again.');}
    finally{setBookingLoading(false)}
  };
  return <div className="site-page"><Header onAdmin={onAdmin}/><main id="top"><section className="hero"><img className="hero-photo" src={photos[0].src} alt="Hotel Bhola Inn exterior"/><div className="hero-overlay"/><div className="hero-grid"/><div className="hero-copy shell"><div className="eyebrow"><span className="dot"/> STATION CHOWK / BETTIAH</div><h1>Stay close<br/><em>to the heart.</em></h1><p>Modern rooms, warm hospitality and an easy base in the centre of Bettiah.</p><div className="hero-links"><a href="#rooms">Explore rooms <ArrowDownRight size={15}/></a><a href="#dining">Dine at Bhola <ArrowUpRight size={15}/></a></div></div><div className="hero-badge">BHOLA<br/><span>INN</span><small>BETTIAH</small></div></section>
  <section className="shell booking-wrap"><BookingBar onSearch={handleSearch}/>{bookingError&&<div className="search-result-note error">{bookingError}</div>}{bookingSearch&&<div className="search-result-note">Showing options for {bookingSearch.checkIn} → {bookingSearch.checkOut}, {bookingSearch.guests} guests. <span>{currentAvailable.length} room types with inventory.</span></div>}</section>
  <section className="section shell intro"><div className="section-no">01</div><div><span className="kicker">A CITY-CENTRE STAY</span><h2>Comfort with a<br/><em>local pulse.</em></h2></div><div className="intro-copy"><p>Hotel Bhola Inn sits at Station Chowk on Supriya Cinema Road, close to Bettiah Railway Station. Public travel listings describe it as a 3-star property with restaurant, room service, air conditioning, parking, laundry and Wi-Fi.</p><p>The website is paired with a management console so the same booking model powers guest-facing discovery and staff operations.</p></div></section>
  <section className="section shell" id="rooms"><div className="section-heading"><div><span className="kicker">ROOMS</span><h2>Sleep well.<br/><em>Stay easy.</em></h2></div><a className="small-link" href="#book">Book a room <ArrowUpRight size={15}/></a></div><div className="room-grid">{rooms.map(r=><article className="room-card" key={r.id}><div className="room-image"><img src={r.image} alt={r.name}/><span>{r.size}</span></div><div className="room-info"><div><h3>{r.name}</h3><p>{r.bed} · {r.guests} guests · {r.bath}</p></div><strong>₹{r.price.toLocaleString('en-IN')}<small>/night</small></strong></div><div className="chip-row">{r.features.slice(0,4).map(f=><span key={f}>{f}</span>)}</div><button onClick={()=>handleReserve(r)} className="card-cta" disabled={bookingSearch ? !availableTypes.some((x:any)=>x.id===r.id&&x.availableRooms>0) : false}>Reserve this room <ArrowUpRight size={15}/></button></article>)}</div></section>
  <section className="section dining-grid shell" id="dining"><div className="dining-photo"><img src={photos[2].src} alt="Hotel Bhola Inn property"/></div><div className="dining-copy"><span className="kicker">DINING</span><h2>A table<br/><em>for your day.</em></h2><p>Public restaurant listings show Hotel Bhola Inn with dining, takeaway and delivery. The official menu is deliberately managed as an admin-uploaded PDF rather than hard-coded from unreliable third-party menu text.</p><a className="outline-btn" href="#menu">View digital menu <ArrowUpRight size={15}/></a></div></section>
  <section className="section shell"><div className="section-heading"><div><span className="kicker">AMENITIES</span><h2>The useful<br/><em>things matter.</em></h2></div></div><div className="amenity-grid">{amenities.map((a,i)=><div key={a}><span>0{i+1}</span><strong>{a}</strong></div>)}</div></section>
  <section className="section shell gallery"><div className="gallery-mosaic">{photos.map((p,i)=><img key={p.src} className={i===0?'large':''} src={p.src} alt={p.label}/>)}</div><div className="gallery-copy"><span className="kicker">THE HOUSE</span><h2>See where<br/><em>you'll stay.</em></h2><p>These prototype media references are visible in public hotel listings. Replace them with hotel-owned or licensed originals through Admin → Gallery & CMS before commercial launch.</p></div></section>
  <section className="section shell review-section"><div><span className="kicker">GUEST VOICE</span><h2>What stays<br/><em>with you.</em></h2><p className="rating-big">3.8 <span>★</span></p><p className="muted">Google-derived listing snapshot</p></div><div className="review-stack">{reviews.slice(0,3).map(r=><article key={r.title}><div className="stars">{'★'.repeat(r.rating)}<span>{r.source}</span></div><h3>{r.title}</h3><p>“{r.text}”</p><small>{r.period}</small></article>)}</div></section>
  <section className="section shell location-section"><div className="location-card"><span className="kicker">FIND US</span><h2>Station Chowk,<br/><em>Bettiah.</em></h2><p>{hotel.address}</p><div className="location-actions"><a href="https://www.google.com/maps/search/?api=1&query=Hotel+Bhola+Inn+Station+Chowk+Bettiah" target="_blank" rel="noreferrer" className="primary-btn">Open maps <ArrowUpRight size={15}/></a><a href={'tel:'+hotel.phone.replace(/\s/g,'')} className="outline-btn">{hotel.phone}</a></div></div><div className="map-placeholder"><div><span>08 MIN WALK</span><strong>Bettiah<br/>Railway Station</strong><small>Public listing reference</small></div></div></section>
  <section className="section shell menu-section" id="menu"><div className="section-heading"><div><span className="kicker">DIGITAL MENU</span><h2>Turn the page.</h2></div><span className="menu-status">Admin-controlled PDF flipbook</span></div><Flipbook file={publishedMenu?.blob||null} fileName={publishedMenu?.name} onUpload={()=>{}}/></section>
  <section className="section shell final-cta" id="book"><span className="kicker">READY WHEN YOU ARE</span><h2>Make Bettiah<br/><em>your base.</em></h2><button className="primary-btn large-btn" onClick={()=>handleSearch({...getDefaultStay(),guests:2})}>Check rooms <ArrowDownRight size={17}/></button></section></main><footer className="footer shell"><div><span className="brand-mark">BI</span> BHOLA INN</div><p>{hotel.address}<br/>{hotel.phone}</p><div><a href="#top">Back to top ↑</a><button onClick={onAdmin}>Open admin ↗</button></div></footer>
  {selectedRoom&&<div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={()=>setSelectedRoom(null)}><X size={18}/></button>{bookingDone?<div className="success-panel"><Check size={28}/><h2>Request received.</h2><p>Your reservation is now in the Hotel Bhola Inn booking system.</p>{bookingConfirmation&&<div className="confirmation-box"><b>{bookingConfirmation.confirmation_code}</b><span>Room {bookingConfirmation.room_number} · ₹{Number(bookingConfirmation.total).toLocaleString('en-IN')}</span></div>}<button className="primary-btn" onClick={()=>{setBookingDone(false);setSelectedRoom(null)}}>Done</button></div>:<form onSubmit={submit}><span className="kicker">RESERVE / {selectedRoom.name.toUpperCase()}</span><h2>Book your stay.</h2><p className="modal-price">₹{selectedRoom.price.toLocaleString('en-IN')} <small>/ night + 12% tax</small></p><label>Guest name<input name="guest" required placeholder="Full name"/></label><label>Phone<input name="phone" required placeholder="+91 …"/></label><label>Email <span>(optional)</span><input name="email" type="email" placeholder="you@example.com"/></label><label>Notes <span>(optional)</span><textarea name="notes" rows={3} placeholder="Special request"/></label>{bookingError&&<p className="form-error">{bookingError}</p>}<button className="primary-btn" type="submit" disabled={bookingLoading}>{bookingLoading?'Submitting…':'Confirm reservation request'} {!bookingLoading&&<ArrowDownRight size={16}/>}</button></form>}</div></div>}</div>
}

function Sidebar({section,setSection,staffName,onSignOut}:{section:string;setSection:(x:string)=>void;staffName:string;onSignOut:()=>void}){return <aside className="admin-sidebar"><div className="admin-brand"><span className="brand-mark">BI</span><div><b>BHOLA INN</b><small>ADMIN CONSOLE</small></div></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}><Icon size={17}/>{label}</button>)}</nav><div className="sidebar-bottom"><div className="admin-user"><div className="avatar">{staffName.slice(0,1).toUpperCase()}</div><div><b>{staffName}</b><small>Staff access</small></div></div><button onClick={onSignOut}><LogOut size={16}/> Sign out</button></div></aside>}
function Stat({title,value,detail,icon:Icon}:any){return <div className="stat-card"><div className="stat-icon"><Icon size={17}/></div><div><span>{title}</span><strong>{value}</strong><small>{detail}</small></div></div>}
function Dashboard({store,occupancy,pending,arrivals,setSection}:any){return <><div className="dashboard-grid"><Stat title="Occupancy" value={occupancy+'%'} detail="Live from reservations" icon={Gauge}/><Stat title="Pending" value={String(pending).padStart(2,'0')} detail="Need confirmation" icon={Clock3}/><Stat title="Arrivals" value={String(arrivals).padStart(2,'0')} detail="Today · 04 Oct" icon={CalendarDays}/><Stat title="Rooms" value={store.rooms.filter((r:any)=>r.status==='clean').length+'/'+store.rooms.length} detail="Clean / total" icon={BedDouble}/></div><div className="two-col"><section className="panel"><div className="panel-head"><div><span className="kicker">BOOKING PIPELINE</span><h2>Latest reservations</h2></div><button onClick={()=>setSection('reservations')}>View all <ChevronRight size={15}/></button></div><div className="data-table"><div className="table-row table-head"><span>Guest</span><span>Stay</span><span>Room</span><span>Status</span><span>Total</span></div>{store.reservations.slice(0,5).map((r:any)=><div className="table-row" key={r.id}><span><b>{r.guest}</b><small>{r.id} · {r.source}</small></span><span>{r.checkIn}<small>→ {r.checkOut}</small></span><span>{r.roomType}<small>{r.roomId}</small></span><span><i className={'status '+r.status}>{r.status}</i></span><span>₹{Number(r.amount).toLocaleString('en-IN')}</span></div>)}</div></section><section className="panel"><div className="panel-head"><div><span className="kicker">HOUSEKEEPING</span><h2>Room floorboard</h2></div></div><div className="room-board">{store.rooms.map((r:any)=><div key={r.id} className={'room-tile '+r.status}><strong>{r.number}</strong><small>{r.status}</small></div>)}</div></section></div><section className="panel"><div className="panel-head"><div><span className="kicker">OPERATIONS</span><h2>Quick actions</h2></div></div><div className="quick-actions">{[['Create reservation','reservations',CalendarDays],['Rooms & inventory','rooms',BedDouble],['Upload menu PDF','dining',FileText],['Website media','media',GalleryHorizontal]].map(([label,id,Icon]:any)=><button key={id} onClick={()=>setSection(id)}><Icon size={17}/><span>{label}</span><ArrowUpRight size={13}/></button>)}</div></section></>}
function Reservations({store,refresh}:any){const [q,setQ]=useState('');const [status,setStatus]=useState('all');const filtered=store.reservations.filter((r:any)=>(status==='all'||r.status===status)&&(!q||[r.guest,r.id,r.phone,r.roomType].join(' ').toLowerCase().includes(q.toLowerCase())));const update=(id:string,nextStatus:string)=>{const next=structuredClone(store);const r=next.reservations.find((x:any)=>x.id===id);try{r.status=transitionReservation(r.status,nextStatus)}catch(e){alert((e as Error).message);return}appendAudit(next,'Reservation '+id+' → '+nextStatus);refresh(next)};return <div className="section-admin"><div className="toolbar"><div className="admin-search wide"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by guest, booking ID or room"/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option>pending</option><option>confirmed</option><option>checked-in</option><option>checked-out</option><option>cancelled</option></select><button className="primary-btn"><Plus size={16}/> New reservation</button></div><section className="panel"><div className="data-table"><div className="table-row table-head"><span>Guest</span><span>Stay</span><span>Room</span><span>Amount</span><span>Status</span><span>Action</span></div>{filtered.map((r:any)=><div className="table-row reserve-row" key={r.id}><span><b>{r.guest}</b><small>{r.phone}</small></span><span>{r.checkIn}<small>→ {r.checkOut} · {r.guests} guest(s)</small></span><span>{r.roomType}<small>{r.roomId}</small></span><span>₹{Number(r.amount).toLocaleString('en-IN')}</span><span><i className={'status '+r.status}>{r.status}</i></span><span className="row-actions">{r.status==='pending'&&<button onClick={()=>update(r.id,'confirmed')}>Confirm</button>}{r.status==='confirmed'&&<button onClick={()=>update(r.id,'checked-in')}>Check in</button>}{r.status==='checked-in'&&<button onClick={()=>update(r.id,'in-house')}>In-house</button>}{r.status==='in-house'&&<button onClick={()=>update(r.id,'checked-out')}>Check out</button>}</span></div>)}</div></section></div>}
function Rooms({store,refresh}:any){const toggle=(id:string)=>{const next=structuredClone(store);const r=next.rooms.find((x:any)=>x.id===id);r.status=r.status==='maintenance'?'clean':'maintenance';appendAudit(next,'Room '+r.number+' marked '+r.status);refresh(next)};return <div className="section-admin"><div className="toolbar"><div><span className="kicker">INVENTORY</span><h2>12 physical rooms configured</h2></div><button className="primary-btn"><Plus size={16}/> Add room</button></div><div className="admin-room-grid">{store.rooms.map((r:any)=><article key={r.id} className="admin-room-card"><div><span className={'room-state '+r.status}>{r.status}</span><strong>{r.number}</strong></div><h3>{r.type}</h3><p>Floor {r.floor} · {r.typeId==='deluxe'?'200 sq ft':'400 sq ft'} · 1 king bed</p><button onClick={()=>toggle(r.id)}>{r.status==='maintenance'?'Mark clean':'Block for maintenance'}</button></article>)}</div></div>}
function Calendar({store}:any){const dates=['04','05','06','07','08','09','10'];return <div className="section-admin"><div className="calendar-head"><span>OCTOBER 2026</span><button className="quiet-btn">Today</button></div><section className="panel calendar-panel"><div className="calendar-grid">{dates.map(d=><div key={d} className="day-col"><div className="day-head"><small>DATE</small><strong>{d}</strong></div>{store.rooms.map((r:any)=><div key={r.id} className="slot"><small>{r.number}</small>{store.reservations.filter((b:any)=>b.roomId===r.id&&b.checkIn<=('2026-10-'+d)&&b.checkOut>('2026-10-'+d)).map((b:any)=><span key={b.id} className={'booking-block '+b.status}>{b.guest}</span>)}</div>)}</div>)}</div></section></div>}
function Dining({menuFile,fileName,setMenu}:any){return <div className="section-admin"><div className="feature-banner"><div><span className="kicker">PDF → FLIPBOOK</span><h2>One upload. A living digital menu.</h2><p>Upload the approved menu PDF once. The asset is stored in IndexedDB for this prototype and immediately becomes available on the public menu surface.</p></div><FileText size={34}/></div><Flipbook file={menuFile} fileName={fileName} onUpload={async(file)=>{await saveMenu(file);setMenu(file,file.name)}}/><div className="panel"><div className="panel-head"><div><span className="kicker">MENU GOVERNANCE</span><h2>Publishing controls</h2></div></div><div className="toggle-row"><div><b>Public menu</b><small>Show the currently uploaded flipbook.</small></div><button className="toggle on"><i/></button></div><div className="toggle-row"><div><b>QR destination</b><small>Use the menu route as the QR scan destination.</small></div><button className="toggle on"><i/></button></div></div></div>}
function Guests({store}:any){return <div className="section-admin"><div className="toolbar"><div><span className="kicker">GUEST CRM</span><h2>Guest history</h2></div></div><section className="panel"><div className="data-table"><div className="table-row table-head"><span>Guest</span><span>Bookings</span><span>Last stay</span><span>Lifetime</span></div>{store.reservations.map((r:any)=><div className="table-row" key={r.id}><span><b>{r.guest}</b><small>{r.phone}</small></span><span>1</span><span>{r.checkOut}</span><span>₹{Number(r.amount).toLocaleString('en-IN')}</span></div>)}</div></section></div>}
function Housekeeping({store,refresh}:any){const setState=(id:string,status:string)=>{const next=structuredClone(store);const r=next.rooms.find((x:any)=>x.id===id);r.status=status;appendAudit(next,'Housekeeping: room '+r.number+' → '+status);refresh(next)};return <div className="section-admin"><div className="admin-room-grid">{store.rooms.map((r:any)=><article className="house-card" key={r.id}><div><strong>Room {r.number}</strong><span className={'room-state '+r.status}>{r.status}</span></div><p>{r.type}</p><div className="house-actions"><button onClick={()=>setState(r.id,'dirty')}>Dirty</button><button onClick={()=>setState(r.id,'cleaning')}>Cleaning</button><button onClick={()=>setState(r.id,'clean')}>Clean</button></div></article>)}</div></div>}
function Payments({store}:any){const collected=store.reservations.reduce((a:number,r:any)=>a+(r.status==='pending'?0:Number(r.amount)),0);const outstanding=store.reservations.reduce((a:number,r:any)=>a+(r.status==='pending'?Number(r.amount):0),0);return <div className="section-admin"><div className="dashboard-grid"><Stat title="Collected" value={'₹'+collected.toLocaleString('en-IN')} detail="Confirmed / completed" icon={ShieldCheck}/><Stat title="Outstanding" value={'₹'+outstanding.toLocaleString('en-IN')} detail="Pending confirmations" icon={Clock3}/></div><section className="panel"><div className="panel-head"><div><span className="kicker">FOLIO VIEW</span><h2>Reservation charges</h2></div></div>{store.reservations.map((r:any)=><div className="audit-row" key={r.id}><span>{r.id} · {r.guest}</span><b>₹{Number(r.amount).toLocaleString('en-IN')}</b></div>)}</section></div>}
function Reviews(){return <div className="section-admin"><div className="dashboard-grid"><Stat title="Google-derived" value="3.8/5" detail="474 votes" icon={MessageSquareText}/><Stat title="MakeMyTrip" value="3.8/5" detail="33 ratings snapshot" icon={MessageSquareText}/></div><section className="panel"><div className="review-admin-grid">{reviews.map(r=><article key={r.title}><div className="stars">{'★'.repeat(r.rating)}<span>{r.source}</span></div><h3>{r.title}</h3><p>“{r.text}”</p><button>Draft response <ArrowUpRight size={14}/></button></article>)}</div></section></div>}
function Media(){return <div className="section-admin"><div className="toolbar"><div><span className="kicker">MEDIA MANAGER</span><h2>Property media</h2></div><button className="primary-btn"><Plus size={16}/> Upload media</button></div><div className="media-grid">{photos.map((p,i)=><article key={p.src}><img src={p.src} alt={p.label}/><div><b>{p.label}</b><small>Public-listing reference · slot {i+1}</small></div></article>)}</div><div className="warning">Replace these research/demo references with client-owned or properly licensed originals before commercial launch.</div></div>}
function SettingsPanel({store,refresh}:any){return <div className="section-admin"><section className="panel settings-panel"><div><span className="kicker">PROPERTY</span><h2>Hotel details</h2></div>{[['Name',hotel.name],['Phone',hotel.phone],['Address',hotel.address],['Check-in',hotel.checkIn],['Check-out',hotel.checkOut]].map(([a,b])=><label key={a}>{a}<input defaultValue={b}/></label>)}<button className="primary-btn" onClick={()=>{const next=structuredClone(store);appendAudit(next,'Property settings viewed / edited');refresh(next)}}>Save changes <Check size={15}/></button></section><section className="panel"><div className="panel-head"><div><span className="kicker">AUDIT LOG</span><h2>Recent activity</h2></div></div>{store.audit.slice(0,14).map((a:any)=><div className="audit-row" key={a.id}><span>{a.action}</span><small>{new Date(a.at).toLocaleString('en-IN')}</small></div>)}</section></div>}
function AdminLogin({onLogin}:{onLogin:(staff:any)=>void}){
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setError('');try{const result=await signInAdmin(email.trim(),password);onLogin(result.staff)}catch(err){setError(err instanceof Error?err.message:'Sign-in failed.')}finally{setLoading(false)}};
  return <div className="login-shell"><div className="login-card"><span className="kicker">HOTEL BHOLA INN / ADMIN</span><h1>Operations access.</h1><p>Sign in with an authorized hotel staff account.</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="username"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></label>{error&&<p className="form-error">{error}</p>}<button className="primary-btn" disabled={loading} type="submit">{loading?'Signing in…':'Sign in'} <ArrowUpRight size={15}/></button></form><a className="small-link" href="#top">← Back to website</a></div></div>
}

function AdminApp({onHome,staff,onSignOut}:{onHome:()=>void;staff:any;onSignOut:()=>void}){const [section,setSection]=useState('dashboard');const [store,setStore]=useState<any>(()=>loadStore());const [liveMode,setLiveMode]=useState(false);const [menuFile,setMenuFile]=useState<Blob|null>(null);const [menuFileName,setMenuFileName]=useState('');
useEffect(()=>{let mounted=true;(async()=>{try{const data=await getAdminData();if(!mounted)return;const hydrated={...loadStore(),reservations:(data.reservations||[]).map((r:any)=>{const guest=Array.isArray(r.guest)?r.guest[0]:r.guest;const room=Array.isArray(r.room)?r.room[0]:r.room;const roomType=room&&Array.isArray(room.room_type)?room.room_type[0]:room?.room_type;return {id:r.id,guest:guest?.full_name||'Guest',phone:guest?.phone||'',roomId:room?.id||'',roomType:roomType?.name||'Room',checkIn:r.check_in,checkOut:r.check_out,guests:r.guests,status:r.status==='checked_in'?'checked-in':r.status==='checked_out'?'checked-out':r.status,amount:Number(r.total),source:r.source}}),rooms:(data.rooms||[]).map((r:any)=>{const rt=Array.isArray(r.room_type)?r.room_type[0]:r.room_type;return {id:r.id,number:r.room_number,floor:r.floor,type:rt?.name||'Room',typeId:rt?.slug||'',status:r.status}})};setStore(hydrated);setLiveMode(true);}catch(error){console.error(error);setLiveMode(false);}})();return()=>{mounted=false}},[]);
const refresh=async(next:any)=>{const prev=store;setStore(next);saveStore(next);if(!liveMode)return;try{const changedReservations=(next.reservations||[]).filter((r:any)=>{const old=(prev.reservations||[]).find((x:any)=>x.id===r.id);return old&&old.status!==r.status&&/^[0-9a-f-]{36}$/i.test(r.id)});for(const r of changedReservations){const dbStatus=r.status==='checked-in'?'checked_in':r.status==='checked-out'?'checked_out':r.status;await updateReservationStatus(r.id,dbStatus)}const changedRooms=(next.rooms||[]).filter((r:any)=>{const old=(prev.rooms||[]).find((x:any)=>x.id===r.id);return old&&old.status!==r.status&&/^[0-9a-f-]{36}$/i.test(r.id)});for(const r of changedRooms){await updateRoomStatus(r.id,r.status)}}catch(error){console.error(error)}};const occupancy=Math.round((store.reservations.filter((r:any)=>['confirmed','checked-in','in-house'].includes(r.status)).length/store.rooms.length)*100);const pending=store.reservations.filter((r:any)=>r.status==='pending').length;const arrivals=store.reservations.filter((r:any)=>r.checkIn==='2026-10-04'&&['pending','confirmed'].includes(r.status)).length;useEffect(()=>{loadMenu().then((m:any)=>{if(m){setMenuFile(m.blob);setMenuFileName(m.name)}})},[]);return <div className="admin-shell"><Sidebar section={section} setSection={setSection} staffName={staff.display_name} onSignOut={onSignOut}/><div className="admin-main"><header className="admin-top"><div><span className="kicker">HOTEL BHOLA INN / OPERATIONS</span><h1>{nav.find(x=>x[0]===section)?.[1]}</h1></div><div className="admin-top-actions"><button className="quiet-btn" onClick={onHome}>View website <ArrowUpRight size={15}/></button><div className="admin-search"><Search size={16}/><input placeholder="Search reservations, guests…"/></div></div></header><div className="admin-body">{section==='dashboard'&&<Dashboard store={store} occupancy={occupancy} pending={pending} arrivals={arrivals} setSection={setSection}/>} {section==='reservations'&&<Reservations store={store} refresh={refresh}/>} {section==='rooms'&&<Rooms store={store} refresh={refresh}/>} {section==='calendar'&&<Calendar store={store}/>} {section==='dining'&&<Dining menuFile={menuFile} fileName={menuFileName} setMenu={(f:any,n:string)=>{setMenuFile(f);setMenuFileName(n)}}/>} {section==='guests'&&<Guests store={store}/>} {section==='housekeeping'&&<Housekeeping store={store} refresh={refresh}/>} {section==='payments'&&<Payments store={store}/>} {section==='reviews'&&<Reviews/>} {section==='media'&&<Media/>} {section==='settings'&&<SettingsPanel store={store} refresh={refresh}/>}</div></div></div>}

export default function App(){
  const [admin,setAdmin]=useState(window.location.hash==='#admin');
  const [authReady,setAuthReady]=useState(false);
  const [staff,setStaff]=useState<any>(null);
  useEffect(()=>{
    const f=()=>setAdmin(window.location.hash==='#admin');
    window.addEventListener('hashchange',f);
    const boot=async()=>{
      if(!supabase){setAuthReady(true);return}
      const {data:{session}}=await supabase.auth.getSession();
      if(session){const {data:profile}=await supabase.from('staff_profiles').select('user_id,display_name,role,active').eq('user_id',session.user.id).eq('active',true).maybeSingle();if(profile)setStaff(profile)}
      setAuthReady(true);
    };
    boot();
    return()=>window.removeEventListener('hashchange',f)
  },[]);
  if(!admin)return <PublicSite onAdmin={()=>{window.location.hash='admin'}}/>;
  if(!authReady)return <div className="login-shell"><div className="login-card"><span className="kicker">HOTEL BHOLA INN</span><h1>Loading secure access…</h1></div></div>;
  if(!supabase)return <div className="login-shell"><div className="login-card"><h1>Supabase not configured.</h1><p>Add the project URL and publishable key to the Vite environment.</p><a className="small-link" href="#top">← Back to website</a></div></div>;
  if(!staff)return <AdminLogin onLogin={setStaff}/>;
  return <AdminApp staff={staff} onSignOut={async()=>{await signOutAdmin();setStaff(null);window.location.hash=''}} onHome={()=>{window.location.hash=''}}/>;
}